### ISSUE TITLE
Build Failure on GHC 8.4.1

### ISSUE THREAD

**Issue by jkachmar** [fpco/odbc#1]
ODBC fails to build with GHC 8.4.1 with the following error:
```
src/Database/ODBC/SQLServer.hs:211:13: error:
    • No instance for (Semigroup Query)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid Query)
    |
211 |   deriving (Monoid, Eq, Show, Typeable, Ord, Generic, Data)
    |  
```

**Comment by chrisdone** [comment]
I'll add GHC build testing to CI!

**Comment by chrisdone** [comment]
Fixed in odbc-0.0.2.
